# Root initializer for COMFYUI_PROMPTMODELS
from .get_last_frame import (
    NODE_CLASS_MAPPINGS as GET_LAST_FRAME_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as GET_LAST_FRAME_NAME_MAPPINGS,
)
from .text_prompt_blocker import (
    NODE_CLASS_MAPPINGS as TEXT_PROMPT_BLOCKER_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as TEXT_PROMPT_BLOCKER_NAME_MAPPINGS,
)
from .DivisorDePrompts import (
    NODE_CLASS_MAPPINGS as DIVISOR_DE_PROMPTS_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as DIVISOR_DE_PROMPTS_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}

NODE_CLASS_MAPPINGS.update(GET_LAST_FRAME_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(GET_LAST_FRAME_NAME_MAPPINGS)

NODE_CLASS_MAPPINGS.update(TEXT_PROMPT_BLOCKER_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(TEXT_PROMPT_BLOCKER_NAME_MAPPINGS)

NODE_CLASS_MAPPINGS.update(DIVISOR_DE_PROMPTS_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(DIVISOR_DE_PROMPTS_NAME_MAPPINGS)

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]

print("[COMFYUI_PROMPTMODELS] ✅ Nodes loaded: GetLastFrame, GetFrameByIndex, TextPromptBlocker, TextPromptBlockerPreview, DivisorDePrompts")
