[project]
name = "promptmodels"
description = "Custom nodes for ComfyUI by PROMPTMODELS."
version = "1.0.4"
license = {file = "LICENSE"}

[project.urls]
Repository = "https://github.com/cdanielp/COMFYUI_PROMPTMODELS"
Documentation = "https://github.com/cdanielp/COMFYUI_PROMPTMODELS/wiki"
"Bug Tracker" = "https://github.com/cdanielp/COMFYUI_PROMPTMODELS/issues"

[tool.comfy]
PublisherId = "promptmodelsstudio"
DisplayName = "COMFYUI_PROMPTMODELS"
Icon = "https://raw.githubusercontent.com/cdanielp/COMFYUI_PROMPTMODELS/main/prompts%20models%20logo.png"
Includes = []
